var searchData=
[
  ['octaves_0',['octaves',['../structfnl__state.html#ad88053ee29c8a0c45281cbc122e22da8',1,'fnl_state']]],
  ['optimisations_5fall_2ecl_1',['optimisations_all.cl',['../mandelbulb_2optimisations__all_8cl.html',1,'(Global Namespace)'],['../mandelbulb__stationary_2optimisations__all_8cl.html',1,'(Global Namespace)'],['../planet_2optimisations__all_8cl.html',1,'(Global Namespace)'],['../sierpinski_2optimisations__all_8cl.html',1,'(Global Namespace)'],['../spheres_2optimisations__all_8cl.html',1,'(Global Namespace)'],['../trivial_2optimisations__all_8cl.html',1,'(Global Namespace)']]],
  ['optimisations_5fbounding_5fvolume_2ecl_2',['optimisations_bounding_volume.cl',['../mandelbulb_2optimisations__bounding__volume_8cl.html',1,'(Global Namespace)'],['../mandelbulb__stationary_2optimisations__bounding__volume_8cl.html',1,'(Global Namespace)'],['../planet_2optimisations__bounding__volume_8cl.html',1,'(Global Namespace)'],['../sierpinski_2optimisations__bounding__volume_8cl.html',1,'(Global Namespace)']]],
  ['optimisations_5fintersection_5fepsilon_2ecl_3',['optimisations_intersection_epsilon.cl',['../mandelbulb_2optimisations__intersection__epsilon_8cl.html',1,'(Global Namespace)'],['../mandelbulb__stationary_2optimisations__intersection__epsilon_8cl.html',1,'(Global Namespace)'],['../planet_2optimisations__intersection__epsilon_8cl.html',1,'(Global Namespace)'],['../sierpinski_2optimisations__intersection__epsilon_8cl.html',1,'(Global Namespace)'],['../spheres_2optimisations__intersection__epsilon_8cl.html',1,'(Global Namespace)']]],
  ['optimisations_5fnone_2ecl_4',['optimisations_none.cl',['../mandelbulb_2optimisations__none_8cl.html',1,'(Global Namespace)'],['../mandelbulb__stationary_2optimisations__none_8cl.html',1,'(Global Namespace)'],['../planet_2optimisations__none_8cl.html',1,'(Global Namespace)'],['../sierpinski_2optimisations__none_8cl.html',1,'(Global Namespace)'],['../spheres_2optimisations__none_8cl.html',1,'(Global Namespace)']]],
  ['override_5',['OVERRIDE',['../mandelbulb_8cl.html#a5dea698950629d9e51d19c1a25be1c30',1,'OVERRIDE():&#160;mandelbulb.cl'],['../mandelbulb__cross__section_8cl.html#a5dea698950629d9e51d19c1a25be1c30',1,'OVERRIDE():&#160;mandelbulb_cross_section.cl']]]
];
